settings:
  digits: '4'
  itemformat: yaml
  prefix: SYS
  sep: '-'

# ITAR Compliance Metadata
# Per DIR-003: Document Configuration File
# Per DIR-007: Requirement Metadata Fields
metadata:
  itar_classification: ITAR CONTROLLED
  export_control: EAR99
  classification: ITAR CONTROLLED - NO FOREIGN PERSONS
  access_level: RESTRICTED
  document_type: System Requirements
  title: System Requirements Specification
  version: 1.0
